
import = ["~/.config/alacritty/themes/tokyo-night/tokyo-night-theme.toml", "~/.config/alacritty/fonts/JetBrainsMono.toml"]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font]
size = 13

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F"
mods = "Command|Control"

[scrolling]
history = 100000
multiplier = 10

[selection]
save_to_clipboard = true
semantic_escape_chars = "|:\"' {}()[]<>"

[window]
padding.x = 10
padding.y = 10
decorations = "Full"
opacity = 0.93
blur = true
dimensions.columns = 90
dimensions.lines = 30
startup_mode = "Maximized"
dynamic_title = true
